version: '3.5'

services:
  redis-server:
    image: redis
    ports:
      - 6379:6379
    environment:
      - VIRTUAL_HOST=redis.localtest.me 
  frontend-server:
    image: frontend
    environment:
      - VIRTUAL_HOST=frontend.localtest.me 
    build:
      context: frontend
      args:
        - API_URL=http://backend.localtest.me:8000
    ports:
      - 5000:5000
  backend-server:
    image: backend
    build: backend
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis-server
      - REDIS_PORT=6379
      - VIRTUAL_HOST=backend.localtest.me
